version: "3.9"

services:
  client:
    build:
      dockerfile: Dockerfile
    image: ${T_BENCH_TASK_DOCKER_CLIENT_IMAGE_NAME}
    container_name: ${T_BENCH_TASK_DOCKER_CLIENT_CONTAINER_NAME}
    command: ["sh", "-c", "sleep infinity"]
    environment:
      - TEST_DIR=${T_BENCH_TEST_DIR:-/app/tests}
    volumes:
      - ${T_BENCH_TASK_LOGS_PATH:-./logs}:/app/logs
      - ${T_BENCH_TASK_AGENT_LOGS_PATH:-./agent_logs}:/app/agent_logs
      - ${TASK_TESTS_PATH}:/app/tests   # dynamically mount the task tests
